"""added individual post feature

Revision ID: 6d89a0b7f737
Revises: 568fcf065c8f
Create Date: 2025-06-11 11:16:39.607439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d89a0b7f737'
down_revision = '568fcf065c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_type', sa.String(length=20), nullable=False, server_default='profile'))
    op.alter_column('post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('post', 'post_type')
    # ### end Alembic commands ###
