"""registrtion page changes

Revision ID: 753c28667b62
Revises: 902ee05dc013
Create Date: 2025-06-10 01:14:37.626330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753c28667b62'
down_revision = '902ee05dc013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'])
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
