"""add image_urls to post

Revision ID: bcf23d13e2e7
Revises: 7e2424c216bf
Create Date: 2025-06-11 13:31:43.588949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf23d13e2e7'
down_revision = '7e2424c216bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_urls')
    # ### end Alembic commands ###
