name: Deploy Flask app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Reset DB and migrations (for dev/test only!)
      - name: Drop all tables in the database
        run: |
          python init_db.py
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Delete migrations directory
        run: |
          rm -rf migrations

      - name: Initialize DB migrations
        run: |
          python db_commands.py init || true
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate migration
        run: |
          python db_commands.py migrate "Auto migration" || true
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Only apply migrations; do not generate or initialize in CI/CD to avoid altering existing tables
      - name: Apply DB migrations
        run: |
          python db_commands.py upgrade
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

# Instructions:
# 1. Paste your actual publish profile XML in the publish-profile field above.
# 2. The app will use the values set by Terraform at runtime.
# 3. The workflow runs on push to main and can be triggered manually. 